### ISSUE TITLE
how do i cite this package?

### ISSUE THREAD

**Issue by martinjankowiak** [zoj613/polyagamma#82]
should i cite "Efficient Bayesian analysis of spatial occupancy models"?

**Comment by zoj613** [comment]
Hi @martinjankowiak , thanks for bringing this to my attention. I'm happy to hear you have this useful in your research.

It is something I haven't thought about at all. The citation you suggest is a bit old since it was written years before I wrote this package. I guess the preferred one since this package has no official manual would be a generic bib citation, like:
```
@misc{bleki_2021,
 title={An efficient and flexible sampler of the Polya-Gamma distribution with a NumPy/SciPy compatible interface.},
 author={Bleki, Zolisa},
 url={https://pypi.org/project/polyagamma/},
 year={2021},
 month={May}
}
```
Or if using APA style:
`Bleki, Z. (2021, May 11). polyagamma: An efficient and flexible sampler of the Polya-Gamma distribution with a NumPy/SciPy compatible interface (Version 1.3.1) [Computer software]. Retrieved from https://pypi.org/project/polyagamma/` .

Let me know if this works for you.
